{
  parserClass="com.weng.demo_man.rosinterface.RosInterfaceParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiImplClassSuffix="Impl"
  psiClassPrefix="RosInterface"
  psiPackage="com.weng.demo_man.psi"
  psiImplPackage="com.weng.demo_man.psi.impl"

  elementTypeHolderClass="com.weng.demo_man.psi.RosInterfaceTypes"
  elementTypeClass="com.weng.demo_man.psi.RosInterfaceElementType"
  tokenTypeClass="com.weng.demo_man.psi.RosInterfaceTokenType"
}

rosInterfaceFile ::= (property|COMMENT|CRLF)*

property ::= (TYPE KEY SEPARATOR VALUE)|(TYPE KEY) {
    pin=3
    recoverWhile="recover_property"
    mixin="com.weng.demo_man.psi.impl.RosInterfaceNamedElementImpl"
    implements="com.weng.demo_man.psi.RosInterfaceNamedElement"
//    methods=[getType getKey getValue getName setName getNameIdentifier]
}

private recover_property ::= !(TYPE|KEY|SEPARATOR|COMMENT)